In [1]:
import numpy as np

In [2]:
#Creating a one dimensional array
lst = list(range(1,6))
print(lst)
print(type(lst))
arr = np.array(lst)
print(arr)
print(type(arr))

[1, 2, 3, 4, 5]
<class 'list'>
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [11]:
#Shaping and reshaping 
#basically shape functions return the number of rows and columns
arr2 = np.array([1,2,3,4,5])
print(arr2.shape)
arr2 = arr2.reshape(1,5)
arr2.shape

(5,)


(1, 5)

In [29]:
#Some inbuilt functions to create arrays

arr3 = np.arange(0,100,10)
print(arr3)

ones_array = np.ones((3,4)) 
print(ones_array)

zeroes_array = np.zeros((3,4))
print(zeroes_array)

number_array = np.full((3,4),5)
print(number_array)

diagonal_array = np.diag(np.array([3,4,5]))
print(diagonal_array)

identity_matrix = np.eye(3)
print(identity_matrix)

[ 0 10 20 30 40 50 60 70 80 90]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[3 0 0]
 [0 4 0]
 [0 0 5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
#Some of the attributes of a array

array = np.array([[1,2,3],[4,5,6]])
print(array)
print(array.shape)
print(array.size)
print(array.ndim)
print(array.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
6
2
int64


In [30]:
#Some of the vectorized operations
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

#Addition of the arrays 
print("Addition : ",arr1+arr2)

#Subraction of the arrays
print("Subraction : ",arr1-arr2)

#Multiplication of the arrays
print("Multiplication : ",arr1*arr2)

#Division of the arrays
print("Division : ",arr2/arr1)

Addition :  [11 22 33 44 55]
Subraction :  [ -9 -18 -27 -36 -45]
Multiplication :  [ 10  40  90 160 250]
Division :  [10. 10. 10. 10. 10.]


In [31]:
#Some universal functions
arr = np.array([2,4,6,8,10])

print("Square root : ",np.sqrt(arr))
print("Sine value : ",np.sin(arr))
print("Log value : ",np.log(arr))

Square root :  [1.41421356 2.         2.44948974 2.82842712 3.16227766]
Sine value :  [ 0.90929743 -0.7568025  -0.2794155   0.98935825 -0.54402111]
Log value :  [0.69314718 1.38629436 1.79175947 2.07944154 2.30258509]


In [34]:
#Array indexing 
array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [43]:
print(array[1:3,0:2])
print(array[0:2,1:3])


[[ 5  6]
 [ 9 10]]
[[2 3]
 [6 7]]


In [44]:
#Some of the statistical methods
data = np.array(list(range(1,11)))

print("Mean = ",np.mean(data)) #To calculate the mean of the data
print("Standard deviation = ",np.std(data)) #To calculate standard deviation
print("Median =",np.median(data)) #TO calculate the median
print("Variance =",np.var(data)) #To calculate the variance

Mean =  5.5
Standard deviation =  2.8722813232690143
Median = 5.5
Variance = 8.25
